import { PregnancyIllustration } from "@/components/illustrations/pregnancy";
import { recordJourneyOutcome, startNewAttempt } from "@/app/inseminacao/actions";
import type { JourneyOutcome } from "@/lib/journey-state";

export function JourneyOutcomeCard({ journeyId, outcome }: { journeyId: string; outcome?: JourneyOutcome | null }) {
  if (outcome === "positive") return <section className="journey-outcome-card is-positive"><PregnancyIllustration /><span className="stage-kicker">Resultado registrado</span><h2>Um novo capítulo começa aqui</h2><p>O Femmea guarda este marco na sua história. Continue seguindo as orientações da equipe que acompanha você.</p></section>;
  if (outcome === "negative") return <section className="journey-outcome-card"><span className="stage-kicker">Resultado registrado</span><h2>Cuide também do que você sente</h2><p>Esta tentativa fica guardada no seu histórico. Quando fizer sentido para você e sua equipe, é possível iniciar uma nova tentativa sem apagar o caminho anterior.</p><form action={startNewAttempt}><input type="hidden" name="journeyId" value={journeyId} /><button className="story-action story-action-primary">Começar nova tentativa</button></form></section>;

  return <section className="journey-outcome-card"><span className="stage-kicker">Quando chegar o momento</span><h2>Registrar resultado</h2><p>Registre apenas o resultado que você obteve. O app não interpreta nem substitui orientação profissional.</p><div className="journey-outcome-actions"><form action={recordJourneyOutcome}><input type="hidden" name="journeyId" value={journeyId} /><input type="hidden" name="outcome" value="positive" /><button>Positivo</button></form><form action={recordJourneyOutcome}><input type="hidden" name="journeyId" value={journeyId} /><input type="hidden" name="outcome" value="negative" /><button>Negativo</button></form><form action={recordJourneyOutcome}><input type="hidden" name="journeyId" value={journeyId} /><input type="hidden" name="outcome" value="inconclusive" /><button>Inconclusivo</button></form></div>{outcome === "inconclusive" && <small className="journey-outcome-note">O último registro ficou como inconclusivo. Você pode registrar um novo resultado quando tiver orientação para repetir o teste.</small>}</section>;
}
